/**
 * Collection of sketch texts. Need to be saved across multiple calls of handleSelection to delete previous sketches.
 * @type {SketchText[]}
 */
let selectionSketches = [];

/**
 * Module to show the user useful information when selecting something in the 3D scene
 */
export class SelectionHelper {
	/**
	 * Main selection handling function
	 * @param event - Mandatory. Event object as generated by core.events.select
	 * @param options - Optional options object that allows you to customize selection behavior.
	 */
	static handleSelection (event, options) {
		core.scene.showOutlines = true;
		core.sketches.visible = true;
		options = initOptions(options);

		resetSelectionSketches();
		if (!event.sceneObject) {
			core.log.debug("UNSELECT");
			return;
		}

		let consoleOutput = "SELECT";
		let posMap = {}
		for(let i = 0; i < event.sceneObjects.length; i++) {
			let sceneObject = event.sceneObjects[i];
			let positionString = "";
			for (let dpName in sceneObject.dockingPoints) {
				let dp = sceneObject.dockingPoints[dpName];
				let pos = dp.position.map(e => round(e, options.dockingPointPrecision).toFixed(3));
				positionString += "\n" + pos + "\t" + dpName;
				if(options.drawDockingPointNames){
					let posStr = pos.toString(); //convert numer-position to strings to use as map key
					if (!posMap[posStr]) {
						posMap[posStr] = [];
					}
					posMap[posStr].push(dp)
				}
			}
			consoleOutput += "\n" + sceneObject.asset.name + "\nDockingPoints:" + positionString;
			if(i !== event.sceneObjects.length - 1){
				consoleOutput += "\n----------------------------------";
			}
		}
		for (let pos in posMap) {
			drawDpText({
				name: posMap[pos].map(e => e.name).join(", "), //concatenate all names
				position: pos.split(",").map(e => parseFloat(e)) //convert map key back to number array for use in API function
			}, options);
		}
		core.log.debug(consoleOutput);	
	}
}

function drawDpText(dp, options) {
	let s = core.sketches.text({
		text: "<- \"" + dp.name +"\"",
		point: dp.position,
		anchorH: "left",
		anchorV: "center",
		highlightColor: options.highlightColor,
		color: options.color,
		angle: options.angle,
		size: options.size
	});
	selectionSketches.push(s);
}

/**
 * Ensures all the options that are optional but not supplied are initialized to their default values
 * @param options {Object} - Options object
 * @returns {Object} - Initialized options object
 */
function initOptions(options) {
	const defaultOptions = {
		dockingPointPrecision: 3,
		drawDockingPointNames: true,
		color: [0, 0, 0, 1],
		angle: 0,
		highlightColor: [0.7, 0.7, 0.7, 0.4],
		size: 12
	};
	if (!options)
		options = {};
	for (let property in defaultOptions) {
		if (!defaultOptions.hasOwnProperty(property)) {
			continue;
		}
		if (!options.hasOwnProperty(property)) {
			options[property] = defaultOptions[property];
		}
	}

	return options;
}

/**
 * Cleans up sketches drawn for previous events
 */
function resetSelectionSketches() {
	for(let s of selectionSketches){
		s.dispose();
	}
	selectionSketches = [];
}

/**
 * Round a number to the specified number of significant digits after the comma
 * @param value - Number to round
 * @param precision - Number of digits to round the value to
 * @returns {number} - Rounded number
 */
function round(value, precision) {
	let multiplier = Math.pow(10, precision || 0);
	return Math.round(value * multiplier) / multiplier;
}
